Repository avinashkranjan/lifeMEDeasy, pull requests merged in 2021-05, with the labels that each got.

#152 Fixed position of Navbar
  src/components/Header.css
  src/components/HeaderComponent.js
  src/components/Navbar.css
Labels: GSSOC21, Level2

#148 Scroll To Top button added on every page.
  ML-Models/Heart-Disease-Classification/readme.md
  db.sqlite3
  package-lock.json
  package.json
  src/App.js
  src/components/ScrollToTop.css
  src/components/ScrollToTop.js
Labels: GSSOC21, Level2

#111 Adding hover effect on navbar
  ML-Models/Heart-Disease-Classification/readme.md
  package-lock.json
  package.json
  src/App.js
  src/components/CovidPatient.js
  src/components/DoctorRegister.js
  src/components/Navbar.css
  src/components/NavbarItem.js
Labels: GSSOC21, Level2

#121 Dark mode
  src/App.css
  src/App.js
  src/components/Appointments.css
  src/components/Appointments.js
  src/components/CovidPatient.js
  src/components/Covidtest.js
  src/components/Doctor.css
  src/components/DoctorRegister.js
  src/components/Emergency.css
  src/components/Emergency.js
  src/components/Login.js
  src/components/PatientRegister.css
  src/components/PatientRegister.js
  src/components/login.css
Labels: GSSOC21, Level3

#156 Earlier the loader disappeared in milliseconds but now its visible properly.
  .eslintrc.json
  src/App.js
Labels: GSSOC21, Level2

#157 Added Custom Scrollbar with Arrow Keys
  src/App.css
  src/assets/downarrow.png
  src/assets/uparrow.png
Labels: GSSOC21, Level2

#158 QA : Format & Lint
  .eslintrc.json
  .flake8
  .github/workflows/qa_checks.yml
  .gitignore
  Chatbot/chatbot.py
  Chatbot/dataset.py
  Chatbot/predict.py
  ML-Models/Heart-Disease-Classification/Model/heart disease classification.py
  ML-Models/Heart-Disease-Classification/heart disease classification.py
  ML-Models/Heart-Disease-Classification/requirements.txt
  README.md
  lifeMEDeasy/admin.py
  lifeMEDeasy/apps.py
  lifeMEDeasy/forms.py
  lifeMEDeasy/keys.py
  lifeMEDeasy/models.py
  lifeMEDeasy/tests.py
  lifeMEDeasy/views.py
  lifeMEDeasy_QA_checks
  manage.py
  reactdjango/asgi.py
  reactdjango/settings.py
  reactdjango/urls.py
  reactdjango/wsgi.py
Labels: GSSOC21, Level2

#163 improving buttons
  src/App.js
  src/components/Appointments.css
  src/components/Appointments.js
  src/components/CovidPatient.js
  src/components/Covidtest.js
  src/components/DoctorRegister.js
  src/components/Emergency.js
  src/components/Forget.js
  src/components/Login.js
  src/components/PatientRegister.css
  src/components/PatientRegister.js
Labels: GSSOC21, Level1

#154 Signin with google button
  package-lock.json
  package.json
  src/components/Appointments.js
  src/components/CovidPatient.js
  src/components/Covidtest.js
  src/components/DoctorRegister.js
  src/components/Emergency.js
  src/components/NavbarItem.js
  src/components/PatientRegister.js
Labels: GSSOC21, Level3

#167 change login image and improve card and remove dummy link from aap.js
  src/assets/Login.svg
  src/assets/login2.png
  src/components/Appointments.js
  src/components/CovidPatient.js
  src/components/Covidtest.js
  src/components/Doctor.css
  src/components/DoctorRegister.js
  src/components/Emergency.js
  src/components/Forget.js
  src/components/Login.js
  src/components/NavbarItem.js
  src/components/PatientRegister.css
  src/components/PatientRegister.js
  src/components/login.css
Labels: GSSOC21, Level2, assigned, enhancement

#166 show/hide password
  package-lock.json
  package.json
  src/components/CovidPatient.js
  src/components/Covidpatient.css
  src/components/Login.js
  src/components/PatientRegister.js
  src/hooks/usePasswordToggle.js
  src/index.js
Labels: GSSOC21, Level2

#175 added flip cards
  src/App.js
  src/components/Cards.jsx
  src/components/cards.css
Labels: GSSOC21, Level2, enhancement

#164 Fix issue #197 Diabetes Prediction
  DiabetesNotebook.ipynb
  diabetes-model (1).pkl
Labels: GSSOC21, Level1, assigned
