Repository avinashkranjan/lifeMEDeasy, pull requests merged in 2021-04, with the labels that each got.

#116 added shellscripts,updated readme and added requirements.txt
  README.md
  requirements.txt
  scripts/startbackend.sh
  scripts/startfrontend.sh
Labels: GSSOC21, Level2

#118 Configures eslint and prettier for frontend
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
Labels: GSSOC21, Level2

#120 Fixes eslint warnings and errors and preetify's the code using prettier
  .eslintignore
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Appointments.css
  src/components/Appointments.js
  src/components/Doctor.css
  src/components/DoctorRegister.js
  src/components/Emergency.css
  src/components/Emergency.js
  src/components/Footer.js
  src/components/FooterStyle.css
  src/components/Header.css
  src/components/HeaderComponent.js
  src/components/Loader/Loader.js
  src/components/Loader/Loader.module.css
  src/components/Login.js
  src/components/Navbar.css
  src/components/NavbarItem.js
  src/components/PatientRegister.css
  src/components/PatientRegister.js
  src/components/login.css
  src/setupTests.js
Labels: GSSOC21, Level2

#122 added login signup functionality,backend database,updated requirements and .gitignore
  .gitignore
  lifeMEDeasy/admin.py
  lifeMEDeasy/forms.py
  lifeMEDeasy/keys.py
  lifeMEDeasy/models.py
  lifeMEDeasy/views.py
  reactdjango/settings.py
  reactdjango/urls.py
  requirements.txt
  src/components/DoctorRegister.js
  src/components/Login.js
  src/components/PatientRegister.js
Labels: GSSOC21, Level3

#105 Installation instructions in README.md
  README.md
Labels: GSSOC21, Level2

#131 Add lint check in Github Actions for frontend application
  .github/workflows/lint.yml
Labels: GSSOC21, Level3

#133 added session management for the website
  lifeMEDeasy/keys.py
  lifeMEDeasy/views.py
  reactdjango/urls.py
  src/components/Login.js
Labels: GSSOC21, Level3

#138 auto merge PR from dependabot
  .github/workflows/automerge.yml
Labels: GSSOC21, Level1, enhancement
