Repository avinashkranjan/lifeMEDeasy, pull requests merged in 2021-03, with the labels that each got.

#67 Update greetings.yml
  .github/workflows/greetings.yml
Labels: GSSOC21, Level0

#76 Added some improvements in the dataset and chatbot
  Chatbot/chatbot.py
  Chatbot/dataset/dataset.csv
  Chatbot/dataset/symptom_Description.csv
  Chatbot/dataset/symptom_precaution.csv
Labels: GSSOC21, Level1

#72 add contributing.md
  CONTRIBUTING.md
Labels: GSSOC21, Level0

#79 Loader added
  package-lock.json
  package.json
  src/App.js
  src/components/Loader/Loader.js
  src/components/Loader/Loader.module.css
Labels: GSSOC21, Level2, enhancement

#83 Markdown error fixed
  CONTRIBUTING.md
Labels: GSSOC21, Level0

#96 solved the issue with footer
  src/components/Footer.js
  src/components/FooterStyle.css
  src/components/Header.css
  src/components/Navbar.css
  src/components/NavbarItem.js
Labels: GSSOC21, Level2

#99 Added auto label for issues
  .github/workflows/issue.yml
Labels: GSSOC21, Level1

#98 Fixed eslint warnings
  package-lock.json
  src/App.js
  src/components/Appointments.js
  src/components/DoctorRegister.js
  src/components/Emergency.js
  src/components/HeaderComponent.js
  src/components/Login.js
  src/components/NavbarItem.js
  src/components/PatientRegister.js
Labels: GSSOC21, Level2
